name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust based on your project's requirements

      - name: Install dependencies
        run: npm install --force  # Consider using npm ci for deterministic installs

      - name: Build the project
        run: npm run build

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: out  # Replace with your output directory if differe
  deploy:
    needs: build
    runs-on: ubuntu-latest  # Adjust based on your deployment environment
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: production-build
          path: out  # Replace with your output directory if different
