name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust based on your project's requirements

      - name: Install dependencies
        run: npm install --force

      - name: Build the project
        run: npm run build

      - name: Deploy (replace with your deployment strategy)
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: out  # Replace with your output directory if different

  # Optional: Deploy to a production environment (replace with your deployment steps)
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest  # Adjust based on your deployment environment
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: production-build
  #         path: out  # Replace with your output directory if different
  #
  #     # Replace these steps with your deployment commands (e.g., SCP, AWS S3 upload)
  #     - run: scp -r out/* your-username@your-server.com:/path/to/deployment/directory
